spring:
  application:
    name: trend-analysis
  datasource:
    url: jdbc:h2:mem:trenddb
#    url: jdbc:h2:file:/data/trenddb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  ai:
    openai:
      api-key: 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
  #    api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-4o-mini